#*******************************************************************************
# Konfiguracja
#*******************************************************************************
# Bazowy obraz
image: ayufan/openshift-cli
# Usługi
services:
  # Docker in Docker
  - docker:dind


# Zmienne
variables:
  # Sterownik
  DOCKER_DRIVER: overlay
  # Adres klastra
  OPENSHIFT_SERVER: https://master.home.lab:8443
  # Domena uruchamianych aplikacji
  OPENSHIFT_DOMAIN: os310.home.lab
  # Nazwa projektu
  CI_PROJECT_NAME: appname


# Środowiska
stages:
  - dev
  - tst
  - prd


#*******************************************************************************
# OpenShift
#*******************************************************************************
.deploy: &deploy
  script:
    # Aplikacja
    - oc get services $APP 2> /dev/null || oc new-app . --name=$APP --strategy=docker
    # Build
    - oc start-build $APP --from-dir=. --follow
    # Ruting
    - oc get routes $APP 2> /dev/null || oc expose service $APP --hostname=$APP_HOST


#*******************************************************************************
# development
#*******************************************************************************
os-deploy-to-development:
  <<: *deploy
  # Środowiska
  stage: dev
  # Uruchamiane przed właściwym wdrożeniem
  before_script:
    # Zalogowanie do klastra
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    # Wybrane lub utworzenie projektu
    - oc project "99-$CI_PROJECT_NAME" 2> /dev/null || oc new-project "99-$CI_PROJECT_NAME"
    # Dodatkowa konfiguracja
    - sed -i "s/srodowisko/dev/" fluent.conf
  # Zmienne
  variables:
    APP: dev-appname
    APP_HOST: $CI_PROJECT_NAME-development.$OPENSHIFT_DOMAIN
  # Środowisko
  environment:
    name: development
    url: http://$CI_PROJECT_NAME-development.$OPENSHIFT_DOMAIN
  # Wdrożenie uruchamiane ręcznie
  when: manual

