source 'https://rubygems.org'
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end
gem 'activemodel' , "~> 4.2.0"
gem 'activerecord', "~> 4.2.0"
gem 'bunny'
gem 'pg',           "~> 0.20"

