image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

build-master:
  stage: build
  script:
    - docker login -u admin -p password https://registry.home.lab:5000
    - docker build --pull -t "registry.home.lab:5000/esb:latest" .
    - docker push registry.home.lab:5000/esb:latest
  only:
    - master
    
development:
  stage: deploy
  script:
    - export NOMAD_ADDR=http://172.28.128.11:4646
    - nomad job run .nomad
  only:
    - master

