# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
# Update apt and get dependencies

echo "-----> DNS + IP "
sudo sed -i "1inameserver 172.28.128.1 " /etc/resolv.conf
eth1=$(ifconfig eth1 | grep inet | head -n 1 | cut -f12 -d" " | cut -d ":" -f2)
echo $eth1

echo "-----> apt-get "
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y unzip curl vim \
    apt-transport-https \
    ca-certificates \
    software-properties-common

echo "-----> server.hcl "
(
cat <<-EOF
log_level = "DEBUG"
data_dir = "/home/vagrant/server1"
server {
    enabled = true
    bootstrap_expect = 1
}
consul {
  address = "`echo $eth1`:8500"
}
EOF
) | tee /home/vagrant/server.hcl


echo "-----> client.hcl "
(
cat <<-EOF
log_level = "DEBUG"
data_dir = "/home/vagrant/client1"
name = "client1"
client {
    enabled = true
    network_interface = "eth1"
    servers = ["`echo $eth1`:4647"]
}
ports {
    http = 5656
}
consul {
  address = "`echo $eth1`:8500"
}
EOF
) | tee /home/vagrant/client.hcl


echo "-----> nomad_server.service "
(
cat <<-EOF
	[Unit]
	Description=nomad server
	Requires=network-online.target
	After=network-online.target
	
	[Service]
	Restart=on-failure
	ExecStart=/usr/bin/nomad agent -config /home/vagrant/server.hcl -bind=`echo $eth1`
	ExecReload=/bin/kill -HUP $MAINPID
	
	[Install]
	WantedBy=multi-user.target
EOF
) | sudo tee /etc/systemd/system/nomad_server.service


echo "-----> nomad_client.service "
(
cat <<-EOF
	[Unit]
	Description=nomad client
	Requires=network-online.target
	After=network-online.target
	
	[Service]
	Restart=on-failure
	ExecStart=/usr/bin/nomad agent -config /home/vagrant/client.hcl -bind=`echo $eth1`
	ExecReload=/bin/kill -HUP $MAINPID
	
	[Install]
	WantedBy=multi-user.target
EOF
) | sudo tee /etc/systemd/system/nomad_client.service


echo "-----> OTHER"
# Download Nomad
NOMAD_VERSION=0.8.1

echo "Fetching Nomad..."
cd /tmp/
curl -sSL https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip -o nomad.zip

echo "Fetching Consul..."
CONSUL_VERSION=1.0.7
curl -sSL https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip > consul.zip

echo "Installing Nomad..."
unzip nomad.zip
sudo install nomad /usr/bin/nomad

sudo mkdir -p /etc/nomad.d
sudo chmod a+w /etc/nomad.d

# Set hostname's IP to made advertisement Just Work
#sudo sed -i -e "s/.*nomad.*/$(ip route get 1 | awk '{print $NF;exit}') nomad/" /etc/hosts

echo "Installing Docker..."
if [[ -f /etc/apt/sources.list.d/docker.list ]]; then
    echo "Docker repository already installed; Skipping"
else
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
fi
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce

# Restart docker to make sure we get the latest version of the daemon if there is an upgrade
sudo service docker restart

# Make sure we can actually use docker as the vagrant user
sudo usermod -aG docker vagrant

echo "Installing Consul..."
unzip /tmp/consul.zip
sudo install consul /usr/bin/consul
(
cat <<-EOF
	[Unit]
	Description=consul agent
	Requires=network-online.target
	After=network-online.target
	
	[Service]
	Restart=on-failure
	ExecStart=/usr/bin/consul agent -bind=`echo $eth1` -client=`echo $eth1` -data-dir=/home/vagrant/consul
	ExecReload=/bin/kill -HUP $MAINPID
	
	[Install]
	WantedBy=multi-user.target
EOF
) | sudo tee /etc/systemd/system/consul.service
sudo systemctl enable consul.service
sudo systemctl start consul

for bin in cfssl cfssl-certinfo cfssljson
do
	echo "Installing $bin..."
	curl -sSL https://pkg.cfssl.org/R1.2/${bin}_linux-amd64 > /tmp/${bin}
	sudo install /tmp/${bin} /usr/local/bin/${bin}
done

echo "Installing autocomplete..."
nomad -autocomplete-install


echo "-----> services startup"
sudo systemctl enable nomad_server.service
sudo systemctl enable nomad_client.service
sudo systemctl start nomad_server
sudo systemctl start nomad_client


echo "-----> docker daemon.json "
sudo touch /etc/docker/daemon.json
(
cat <<-EOF
{ "insecure-registries":["registry.home.lab:5000"] }
EOF
) | sudo tee /etc/docker/daemon.json
sudo service docker restart

echo "<----- FINISH"
SCRIPT


Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04" # 16.04 LTS
  config.vm.hostname = "nomad"
  config.vm.provision "shell", inline: $script, privileged: false
  config.vm.provision "docker" # Just install it
  
  # Expose the nomad api and ui to the host
  config.vm.network "forwarded_port", guest: 4646, host: 4646, auto_correct: true
  config.vm.network "private_network", type: "dhcp"

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "1024"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "1024"
    end
  end
end

