source 'https://rubygems.org'
ruby '2.5.3'
gem 'railties', '5.2.1', require: %w(action_controller rails)
gem 'coderay'
gem 'markaby'
gem 'bunny'
group :test do
  gem "rack-test", require: false
end
gem "puma"

